
use stage_compras_pyspark;

CREATE TABLE PAGAMENTOS_EFETUADOS(
	ID_NF_ENTRADA int NULL,
	DATA_VENCIMENTO date NULL,
	DATA_PGT_EFETUADO date NULL,
	VALOR_PARCELA_PAGO decimal(16, 2) NULL
);

CREATE TABLE COMPRAS(
    NOME_FORNECEDOR varchar(100) NULL,
    CNPJ_FORNECEDOR varchar(100) NULL,
    EMAIL_FORNECEDOR varchar(100) NULL,
    TELEFONE_FORNECEDOR varchar(20) NULL,
    NUMERO_NF varchar(100) NULL,
    DATA_EMISSAO date NULL,
    VALOR_NET decimal(20, 2) NULL,
    VALOR_TRIBUTO decimal(20, 2) NULL,
    VALOR_TOTAL decimal(20, 2) NULL,
    NOME_ITEM varchar(100) NULL,
    QTD_ITEM int NULL,
    CONDICAO_PAGAMENTO varchar(100) NULL,
    CEP int NULL,
    NUM_ENDERECO int NULL,
    COMPLEMENTO varchar(100) NULL,
    TIPO_ENDERECO varchar(100) NULL,
    DATA_PROCESSAMENTO date NULL
);

CREATE TABLE VALIDACAO_COMPRAS(
	DATA_PROCESSAMENTO date NULL,
	DATA_EMISSAO date NULL,
	NUMERO_NF VARCHAR(100) NULL,
	CNPJ_FORNECEDOR VARCHAR(100) NULL
);

CREATE TABLE VALIDACAO_COMPRAS_REJEITADOS(
	NOME_FORNECEDOR varchar(100) NULL,
	CNPJ_FORNECEDOR varchar(100) NULL,
	EMAIL_FORNECEDOR varchar(100) NULL,
	TELEFONE_FORNECEDOR varchar(20) NULL,
	NUMERO_NF varchar(100) NULL,
	DATA_EMISSAO date NULL,
	VALOR_NET decimal(20, 2) NULL,
	VALOR_TRIBUTO decimal(20, 2) NULL,
	VALOR_TOTAL decimal(20, 2) NULL,
	NOME_ITEM varchar(100) NULL,
	QTD_ITEM int NULL,
	ID_CONDICAO_PAGAMENTO varchar(100) NOT NULL,
	CEP int NULL,
	NUM_ENDERECO int NULL,
	COMPLEMENTO varchar(100) NOT NULL,
	TIPO_ENDERECO varchar(100) NULL,
	DATA_PROCESSAMENTO date NULL,
	MOTIVO_REJEITADO varchar(200) NULL
);

CREATE TABLE CEP(
    CEP nvarchar(20) NULL,
    UF_ENDERECO nvarchar(100) NULL,
    CIDADE_ENDERECO nvarchar(200) NULL,
    BAIRRO_ENDERECO nvarchar(200) NULL,
    NOME_ENDERECO nvarchar(200) NULL
);

CREATE TABLE PAGAMENTOS_EFETUADOS_REJEITADOS(
	ID_NF_ENTRADA int NULL,
	DATA_VENCIMENTO varchar(200) NULL,
	DATA_PGT_EFETUADO varchar(200) NULL,
	VALOR_PARCELA_PAGO decimal(16, 2) NULL,
	MOTIVO_INEXISTENCIA varchar(200) NULL,
	MOTIVO_NULL varchar(200) NULL
);
CREATE TABLE PAGAMENTOS_EFETUADOS_REJEITADOS1(
	ID_NF_ENTRADA int NULL,
	DATA_VENCIMENTO varchar(200) NULL,
	DATA_PGT_EFETUADO varchar(200) NULL,
	VALOR_PARCELA_PAGO decimal(16, 2) NULL,
	MOTIVO_INEXISTENCIA varchar(200) NULL,
	MOTIVO_NULL varchar(200) NULL
);

CREATE TABLE TRATAMENTO_PAGAMENTOS_EFETUADOS (
	ID_NF_ENTRADA INT,
	DATA_VENCIMENTO DATE,
    	DATA_PGT_EFETUADO DATE,
	VALOR_PARCELA_PAGO DECIMAL(10, 2)
);
CREATE TABLE IF NOT EXISTS TRATAMENTO_COMPRAS_FINAL (
    NOME_FORNECEDOR VARCHAR(255),
    CNPJ_FORNECEDOR VARCHAR(14),
    EMAIL_FORNECEDOR VARCHAR(255),
    TELEFONE_FORNECEDOR VARCHAR(20),
    NUMERO_NF INT,
    DATA_EMISSAO DATE,
    VALOR_NET DECIMAL(10,2),
    VALOR_TRIBUTO DECIMAL(10,2),
    VALOR_TOTAL DECIMAL(10,2),
    NOME_ITEM VARCHAR(255),
    QTD_ITEM INT,
    ID_CONDICAO_PAGAMENTO INT,
    CEP VARCHAR(10),
    NUM_ENDERECO INT,
    COMPLEMENTO VARCHAR(255),
    TIPO_ENDERECO VARCHAR(50),
    DATA_PROCESSAMENTO DATE
);

